import yaml
import subprocess
import glob
import os

def run_variance_evaluations(max_layers=4, base_yaml_path="configs/experiments/scaling_ac_smoke.yaml"):
    print("Starting Automated Variance Evaluation for Layer-Wise Checkpoints...\n")
    
    for lap in range(1, max_layers + 1):
        print(f"{'='*50}")
        print(f" EVALUATING LAP {lap} VARIANCE")
        print(f"{'='*50}")
        
        with open(base_yaml_path, 'r') as f:
            config = yaml.safe_load(f)
            
        config['circuit']['n_generators'] = f"{lap}*n"
        
        base_output = "results/patch_test"
        config['experiment']['output_dir'] = f"{base_output}/lap_{lap}"
        
        # Find checkpoint generated by your run_training script
        search_path = f"{base_output}/lap_{lap}/runs/*/checkpoints/step_*.npz"
        checkpoints = glob.glob(search_path)
        
        if not checkpoints:
            print(f"-> Skipping Lap {lap}: Could not find checkpoint file.")
            continue
            
        latest_checkpoint = max(checkpoints, key=os.path.getmtime)
        print(f"-> Found trained foundation: {latest_checkpoint}")
        
        # inject trained parameters so the variance script evaluates the TRAINED model
        config['param_init_file'] = latest_checkpoint
        
        temp_yaml = f"configs/experiments/temp_variance_L{lap}.yaml"
        with open(temp_yaml, 'w') as f:
            yaml.dump(config, f)
            
        command = f"python -m iqp_bp.experiments.run_patch_variance --hyperparams {temp_yaml}"
        
        try:
            subprocess.run(command, shell=True, check=True)
            print(f"Lap {lap} variance calculated successfully!\n")
        except subprocess.CalledProcessError:
            print(f"Lap {lap} variance calculation failed.\n")

if __name__ == "__main__":
    run_variance_evaluations(max_layers=4)